<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Taller evaluado II</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="taller2_enunciado (1)_files/libs/clipboard/clipboard.min.js"></script>
<script src="taller2_enunciado (1)_files/libs/quarto-html/quarto.js"></script>
<script src="taller2_enunciado (1)_files/libs/quarto-html/popper.min.js"></script>
<script src="taller2_enunciado (1)_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="taller2_enunciado (1)_files/libs/quarto-html/anchor.min.js"></script>
<link href="taller2_enunciado (1)_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="taller2_enunciado (1)_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="taller2_enunciado (1)_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="taller2_enunciado (1)_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="taller2_enunciado (1)_files/libs/bootstrap/bootstrap-1bc8a17f135ab3d594c857e9f48e611b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#realizad-un-análisis-exploratorio-multivariante-del-conjunto-de-datos.-para-ello-presentad-e-interpretad-cada-uno-de-los-gráficos-solicitados-a-continuación-relacionándolos-con-el-contexto-del-problema-y-destacando-los-patrones-asociaciones-o-diferencias-relevantes-que-aporten-información-útil-para-comprender-el-uso-de-la-ia-en-los-distintos-sectores-1-punto" id="toc-realizad-un-análisis-exploratorio-multivariante-del-conjunto-de-datos.-para-ello-presentad-e-interpretad-cada-uno-de-los-gráficos-solicitados-a-continuación-relacionándolos-con-el-contexto-del-problema-y-destacando-los-patrones-asociaciones-o-diferencias-relevantes-que-aporten-información-útil-para-comprender-el-uso-de-la-ia-en-los-distintos-sectores-1-punto" class="nav-link active" data-scroll-target="#realizad-un-análisis-exploratorio-multivariante-del-conjunto-de-datos.-para-ello-presentad-e-interpretad-cada-uno-de-los-gráficos-solicitados-a-continuación-relacionándolos-con-el-contexto-del-problema-y-destacando-los-patrones-asociaciones-o-diferencias-relevantes-que-aporten-información-útil-para-comprender-el-uso-de-la-ia-en-los-distintos-sectores-1-punto">1. Realizad un análisis exploratorio multivariante del conjunto de datos. Para ello presentad e interpretad cada uno de los gráficos solicitados a continuación, relacionándolos con el contexto del problema y destacando los patrones, asociaciones o diferencias relevantes que aporten información útil para comprender el uso de la IA en los distintos sectores (1 punto)</a></li>
  <li><a href="#considerad-el-vector-multivariante-mathbfy-definido-a-continuación-para-llevar-a-cabo-el-contraste-de-comparación-de-medias-entre-los-sectores-educación-y-salud-tal-y-como-se-especifica-más-adelante." id="toc-considerad-el-vector-multivariante-mathbfy-definido-a-continuación-para-llevar-a-cabo-el-contraste-de-comparación-de-medias-entre-los-sectores-educación-y-salud-tal-y-como-se-especifica-más-adelante." class="nav-link" data-scroll-target="#considerad-el-vector-multivariante-mathbfy-definido-a-continuación-para-llevar-a-cabo-el-contraste-de-comparación-de-medias-entre-los-sectores-educación-y-salud-tal-y-como-se-especifica-más-adelante.">2. Considerad el vector multivariante <span class="math inline">\(\mathbf{Y}\)</span>, definido a continuación, para llevar a cabo el contraste de comparación de medias entre los sectores Educación y Salud, tal y como se especifica más adelante.</a>
  <ul>
  <li><a href="#a.-qué-supuestos-deben-cumplirse-y-mencionad-cómo-podríais-verificarlos-para-que-sea-válido-aplicar-uno-de-los-test-estudiados-en-la-asignatura-1-punto" id="toc-a.-qué-supuestos-deben-cumplirse-y-mencionad-cómo-podríais-verificarlos-para-que-sea-válido-aplicar-uno-de-los-test-estudiados-en-la-asignatura-1-punto" class="nav-link" data-scroll-target="#a.-qué-supuestos-deben-cumplirse-y-mencionad-cómo-podríais-verificarlos-para-que-sea-válido-aplicar-uno-de-los-test-estudiados-en-la-asignatura-1-punto">a. ¿Qué supuestos deben cumplirse y mencionad cómo podríais verificarlos para que sea válido aplicar uno de los test estudiados en la asignatura? (1 punto)</a></li>
  <li><a href="#b.-escribid-un-código-en-r-que-implemente-el-contraste-de-comparación-de-medias-multivariantes-apropiado-entre-los-sectores-educación-y-salud-para-las-variables-consideradas.-el-código-debe-calcular-y-mostrar-el-vector-de-medias-muestrales-de-cada-sector-ejecutar-el-contraste.-luego-reportad-el-p-valor-y-tomar-una-decisión-para-alpha0.05-en-el-contexto-del-problema-2-puntos" id="toc-b.-escribid-un-código-en-r-que-implemente-el-contraste-de-comparación-de-medias-multivariantes-apropiado-entre-los-sectores-educación-y-salud-para-las-variables-consideradas.-el-código-debe-calcular-y-mostrar-el-vector-de-medias-muestrales-de-cada-sector-ejecutar-el-contraste.-luego-reportad-el-p-valor-y-tomar-una-decisión-para-alpha0.05-en-el-contexto-del-problema-2-puntos" class="nav-link" data-scroll-target="#b.-escribid-un-código-en-r-que-implemente-el-contraste-de-comparación-de-medias-multivariantes-apropiado-entre-los-sectores-educación-y-salud-para-las-variables-consideradas.-el-código-debe-calcular-y-mostrar-el-vector-de-medias-muestrales-de-cada-sector-ejecutar-el-contraste.-luego-reportad-el-p-valor-y-tomar-una-decisión-para-alpha0.05-en-el-contexto-del-problema-2-puntos">b. Escribid un código en R que implemente el contraste de comparación de medias multivariantes apropiado entre los sectores Educación y Salud para las variables consideradas. El código debe calcular y mostrar el vector de medias muestrales de cada sector; ejecutar el contraste. Luego, reportad el p-valor y tomar una decisión para <span class="math inline">\(\alpha=0.05\)</span> en el contexto del problema (2 puntos)</a></li>
  </ul></li>
  <li><a href="#representad-de-manera-reducida-los-perfiles-multivariantes-del-uso-de-ia-del-sector-educación-y-del-sector-salud-por-separado.-interpretad-las-componentes-retenidas-explicando-su-posible-significado-práctico-en-el-contexto-del-problema.-justificad-bien-el-procedimiento-3-puntos" id="toc-representad-de-manera-reducida-los-perfiles-multivariantes-del-uso-de-ia-del-sector-educación-y-del-sector-salud-por-separado.-interpretad-las-componentes-retenidas-explicando-su-posible-significado-práctico-en-el-contexto-del-problema.-justificad-bien-el-procedimiento-3-puntos" class="nav-link" data-scroll-target="#representad-de-manera-reducida-los-perfiles-multivariantes-del-uso-de-ia-del-sector-educación-y-del-sector-salud-por-separado.-interpretad-las-componentes-retenidas-explicando-su-posible-significado-práctico-en-el-contexto-del-problema.-justificad-bien-el-procedimiento-3-puntos">3. Representad de manera reducida los perfiles multivariantes del uso de IA del sector Educación y del sector Salud (por separado). Interpretad las componentes retenidas, explicando su posible significado práctico en el contexto del problema. Justificad bien el procedimiento (3 puntos)</a></li>
  <li><a href="#a-continuación-os-presentamos-dos-bloques-de-código.-explicad-de-forma-breve-qué-procedimiento-estadístico-se-aplica-en-cada-bloque.-después-interpretad-los-resultados-en-el-contexto-del-problema-describid-qué-perfiles-de-uso-de-ia-emergen-en-el-sector-educación-y-en-qué-se-diferencian-entre-sí.-por-último-compara-ambos-bloques-y-justificad-cuál-de-los-dos-resultados-consideráis-más-adecuado-para-describir-los-perfiles-3-puntos" id="toc-a-continuación-os-presentamos-dos-bloques-de-código.-explicad-de-forma-breve-qué-procedimiento-estadístico-se-aplica-en-cada-bloque.-después-interpretad-los-resultados-en-el-contexto-del-problema-describid-qué-perfiles-de-uso-de-ia-emergen-en-el-sector-educación-y-en-qué-se-diferencian-entre-sí.-por-último-compara-ambos-bloques-y-justificad-cuál-de-los-dos-resultados-consideráis-más-adecuado-para-describir-los-perfiles-3-puntos" class="nav-link" data-scroll-target="#a-continuación-os-presentamos-dos-bloques-de-código.-explicad-de-forma-breve-qué-procedimiento-estadístico-se-aplica-en-cada-bloque.-después-interpretad-los-resultados-en-el-contexto-del-problema-describid-qué-perfiles-de-uso-de-ia-emergen-en-el-sector-educación-y-en-qué-se-diferencian-entre-sí.-por-último-compara-ambos-bloques-y-justificad-cuál-de-los-dos-resultados-consideráis-más-adecuado-para-describir-los-perfiles-3-puntos">4. A continuación os presentamos dos bloques de código. Explicad de forma breve qué procedimiento estadístico se aplica en cada bloque. Después, interpretad los resultados en el contexto del problema: describid qué perfiles de uso de IA emergen en el sector Educación y en qué se diferencian entre sí. Por último, compara ambos bloques y justificad cuál de los dos resultados consideráis más adecuado para describir los perfiles (3 puntos)</a>
  <ul>
  <li><a href="#bloque-a" id="toc-bloque-a" class="nav-link" data-scroll-target="#bloque-a">Bloque A</a></li>
  <li><a href="#bloque-b" id="toc-bloque-b" class="nav-link" data-scroll-target="#bloque-b">Bloque B</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Taller evaluado II</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">17 de octubre de 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><strong>Nombre y apellido de cada miembro del grupo</strong></p>
<ul>
<li>Javier Peña Vior</li>
<li>Sara Blanco Sanz</li>
<li>Rubén López Cáceres</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyverse' was built under R version 4.5.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.5.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'stringr' was built under R version 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lubridate' was built under R version 4.5.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'factoextra' was built under R version 4.5.2</code></pre>
</div>
</div>
<p><strong>Una consultora especializada en evaluación y gobernanza de sistemas de Inteligencia Artificial (IA) ha recopilado información de 240 organizaciones pertenecientes a los sectores de Salud y Educación que han incorporado sistemas de IA para apoyar la toma de decisiones y la automatización de procesos.</strong></p>
<p><strong>Para cada organización se ha medido:</strong></p>
<ul>
<li><p><code>ID</code>: Identificador único de la organización/entidad observada.</p></li>
<li><p><code>Sector</code>: Sector al que pertenece la organización (Salud o Educación).</p></li>
<li><p><code>Implementacion</code>: Estado de despliegue de la solución de IA (Piloto o Producción).</p></li>
<li><p><code>Precision</code>: Precisión del sistema en escala 0–100 (a mayor valor, mejor).</p></li>
<li><p><code>Robustez</code>: Estabilidad del sistema ante cambios/ruido/datos distintos en escala 0–100 (a mayor valor, más robusto).</p></li>
<li><p><code>Productividad</code>: Ganancia o nivel de productividad asociado al uso de IA en escala 0–100 (a mayor valor, mejor).</p></li>
<li><p><code>Ahorro_tiempo</code>: Ahorro de tiempo atribuible a la IA en escala 0–100 (a mayor valor, más ahorro).</p></li>
<li><p><code>Riesgo_etico</code>: Nivel de riesgo ético percibido en escala 0–100 (a mayor valor, más riesgo).</p></li>
<li><p><code>Riesgo_legal</code>: Nivel de riesgo legal/regulatorio percibido en escala 0–100 (a mayor valor, más riesgo).</p></li>
<li><p><code>Aceptacion_usuarios</code>: Grado de aceptación por parte de usuarios finales en escala 0–100 (a mayor valor, más aceptación).</p></li>
<li><p><code>Coste</code>: Coste relativo del proyecto/solución en escala 0–100 (a mayor valor, mayor coste).</p></li>
</ul>
<p><strong>El objetivo del estudio es comprender patrones de adopción, similitudes entre organizaciones y posibles diferencias sistemáticas entre grupos.</strong></p>
<p><strong>Los datos están disponibles en el archivo: “datos_taller_evaluado_2.csv”</strong></p>
<section id="realizad-un-análisis-exploratorio-multivariante-del-conjunto-de-datos.-para-ello-presentad-e-interpretad-cada-uno-de-los-gráficos-solicitados-a-continuación-relacionándolos-con-el-contexto-del-problema-y-destacando-los-patrones-asociaciones-o-diferencias-relevantes-que-aporten-información-útil-para-comprender-el-uso-de-la-ia-en-los-distintos-sectores-1-punto" class="level4">
<h4 class="anchored" data-anchor-id="realizad-un-análisis-exploratorio-multivariante-del-conjunto-de-datos.-para-ello-presentad-e-interpretad-cada-uno-de-los-gráficos-solicitados-a-continuación-relacionándolos-con-el-contexto-del-problema-y-destacando-los-patrones-asociaciones-o-diferencias-relevantes-que-aporten-información-útil-para-comprender-el-uso-de-la-ia-en-los-distintos-sectores-1-punto">1. Realizad un análisis exploratorio multivariante del conjunto de datos. Para ello presentad e interpretad cada uno de los gráficos solicitados a continuación, relacionándolos con el contexto del problema y destacando los patrones, asociaciones o diferencias relevantes que aporten información útil para comprender el uso de la IA en los distintos sectores (1 punto)</h4>
<ul>
<li><strong>Una matriz de gráficos de dispersión que incluya las correlaciones entre las variables: <code>Precisión</code>, <code>Robustez</code>, <code>Productividad</code>, <code>Ahorro_tiempo</code> y <code>Aceptacion_usuarios</code>por <code>Sector</code></strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>datos_taller_evaluado_2 <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">"datos_taller_evaluado_2.csv"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 240 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): ID, Sector, Implementacion
dbl (8): Precision, Robustez, Productividad, Ahorro_tiempo, Riesgo_etico, Ri...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(datos_taller_evaluado_2)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 240 × 11
   ID     Sector   Implementacion Precision Robustez Productividad Ahorro_tiempo
   &lt;chr&gt;  &lt;chr&gt;    &lt;chr&gt;              &lt;dbl&gt;    &lt;dbl&gt;         &lt;dbl&gt;         &lt;dbl&gt;
 1 Org001 Salud    Producción          62.4     51.2          87.7          85.4
 2 Org002 Salud    Producción          76.8     70.4          91.7          88.5
 3 Org003 Salud    Piloto              98.5     85.2          83.5          63.1
 4 Org004 Salud    Producción          79.0     63.9          65.8          60.2
 5 Org005 Salud    Producción          93.5     78.0          61.2          43.5
 6 Org006 Salud    Piloto              89.4     64.2          79.7          71.8
 7 Org007 Educaci… Piloto              52.7     64.0          87.7          64.6
 8 Org008 Salud    Producción          87.3     79.6          77.1          64.2
 9 Org009 Educaci… Producción          77.1     77.1          91.2          79.5
10 Org010 Educaci… Piloto              88.9     67.9         100           100  
# ℹ 230 more rows
# ℹ 4 more variables: Riesgo_etico &lt;dbl&gt;, Riesgo_legal &lt;dbl&gt;,
#   Aceptacion_usuarios &lt;dbl&gt;, Coste &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(datos_taller_evaluado_2)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 11
  ID     Sector Implementacion Precision Robustez Productividad Ahorro_tiempo
  &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;              &lt;dbl&gt;    &lt;dbl&gt;         &lt;dbl&gt;         &lt;dbl&gt;
1 Org001 Salud  Producción          62.4     51.2          87.7          85.4
2 Org002 Salud  Producción          76.8     70.4          91.7          88.5
3 Org003 Salud  Piloto              98.5     85.2          83.5          63.1
4 Org004 Salud  Producción          79.0     63.9          65.8          60.2
5 Org005 Salud  Producción          93.5     78.0          61.2          43.5
6 Org006 Salud  Piloto              89.4     64.2          79.7          71.8
# ℹ 4 more variables: Riesgo_etico &lt;dbl&gt;, Riesgo_legal &lt;dbl&gt;,
#   Aceptacion_usuarios &lt;dbl&gt;, Coste &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>perfil_Edu <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">"perfil_Edu.csv"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 116 Columns: 1
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (1): x

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(perfil_Edu)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 1
      x
  &lt;dbl&gt;
1     3
2     3
3     3
4     2
5     2
6     3</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="taller2_enunciado--1-_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Podríamos clasificar las variables en dos subgrupos. Siendo uno de los subgrupos los que presentan una clara correlació lineal directa y el otro los que muestran un gráfico de puntos dispersos sin estructura clara.</p>
<p>A nivel de distribuciones podemos ver que siguen en su mayoría una distribución similar a la normal, binormal o trinormal.</p>
<p>Las que tienen correlación lineal serían precisión-robustez, productividad-ahoro tiempo, productiviad-aceptación usuario y aceptación usuario-ahorro tiempo. A nivel numérico, todo los datos presentan una correlación de entorno al 0.7-0.8 y dos o tres estrellas. Es decir, una correlación lineal relevante.No se observan claras diferencias entre los grupos de salud y de educación. Sí que hay que destacar que las correlaciones de educación son en todos los casos ligeramente menores que las del sector de la salud.</p>
<p>El resto no tienen una correlación entre ellas clara. A nivel numérico inician el valors próximos a 0 (positivos o negativos) y alcanzan un máximo de 0.5, siendo menos significativas que en caso anterior (algunos no tienen estrellas). Excepto en el caso robustez-aceptación usuarios, en todo los casos observamos que el grupo asociado a la educación tiene una correlación ligeramente menor que el grupo asociado a la salud.</p>
<p>En el contexto del problema, observamos que la robustez y la precisión es lógico que tenga una relación ya que cambios en los resultados produciría peores resultados, y viceversa. Un argumento similar nos serviría para la productividad y el ahorro de tiempo. También es lógico que a los usuarios les guste más un programa con mejores resultados y que tarde menos en dar respuesta.</p>
<ul>
<li><strong>Una matriz de gráficos de dispersión que incluya las correlaciones entre las variables: <code>Riesgo_etico</code>, <code>Riesgo_legal</code> y <code>Coste</code> por <code>Sector</code></strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  datos_taller_evaluado_2,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">columns =</span> <span class="fu">c</span>(</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Riesgo_etico"</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Riesgo_legal"</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Coste"</span>),</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">color =</span> Sector, <span class="at">alpha =</span> <span class="fl">0.7</span>),</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">upper =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="fu">wrap</span>(<span class="st">"cor"</span>, <span class="at">size =</span> <span class="dv">4</span>)),</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">lower =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="fu">wrap</span>(<span class="st">"points"</span>, <span class="at">size =</span> <span class="fl">1.5</span>)),</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">diag =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="fu">wrap</span>(<span class="st">"densityDiag"</span>))</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="taller2_enunciado--1-_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Podemos ver una clara correlación lineal de las variables dos a dos, ya que las gráficas visualmente representan una recta creciente en los tres gráficos. Podemos ver que esta correlación sucede tanto en educación como en salud y que los datos no presentan una clara diferencia entre grupos. Más bien se observa una heterogeneidad de los datos entre grupos.</p>
<p>En relación a las distribuciones, podemos ver que todas siguen una representación similar a la binormal.</p>
<p>A nivel numérico observamos que los datos presentan una correlación superior al 0.67 alcanzando casi el 0.9 (entre las variables de riegos). Además todas ellas tienen tres estrellas lo que significa que todas ellas son significativas. En estas variables observamos que, al contrario que las variables anteriores, el grupo asociado a la salud presenta unos valores de correlación ligeramente menores que el de la salud.</p>
<p>Si nos transladamos al contexto del problema podemos ver que los riesgos tanto éticos como legales impactan en el coste del proyecto haciendo que éste sea más caro. El lógico que esto suceda ya que supone realizar más análisis y evaluaciones para cercionarse de que sea seguro para los usuarios.</p>
</section>
<section id="considerad-el-vector-multivariante-mathbfy-definido-a-continuación-para-llevar-a-cabo-el-contraste-de-comparación-de-medias-entre-los-sectores-educación-y-salud-tal-y-como-se-especifica-más-adelante." class="level4">
<h4 class="anchored" data-anchor-id="considerad-el-vector-multivariante-mathbfy-definido-a-continuación-para-llevar-a-cabo-el-contraste-de-comparación-de-medias-entre-los-sectores-educación-y-salud-tal-y-como-se-especifica-más-adelante.">2. Considerad el vector multivariante <span class="math inline">\(\mathbf{Y}\)</span>, definido a continuación, para llevar a cabo el contraste de comparación de medias entre los sectores Educación y Salud, tal y como se especifica más adelante.</h4>
<p><span class="math display">\[
\mathbf{Y}=
\begin{aligned}[t]
(&amp;\texttt{Precision},\ \texttt{Robustez},\ \texttt{Productividad},\ \texttt{Ahorro\_tiempo},\ \texttt{Aceptacion\_usuarios},\\
&amp;\texttt{Riesgo\_etico},\ \texttt{Riesgo\_legal},\ \texttt{Coste})
\end{aligned}
\]</span></p>
<p><span class="math display">\[
H_0:\ \boldsymbol{\mu}_{\text{Edu}}=\boldsymbol{\mu}_{\text{Salud}}
\qquad \text{frente a} \qquad
H_1:\ \boldsymbol{\mu}_{\text{Edu}}\neq \boldsymbol{\mu}_{\text{Salud}}.
\]</span></p>
<section id="a.-qué-supuestos-deben-cumplirse-y-mencionad-cómo-podríais-verificarlos-para-que-sea-válido-aplicar-uno-de-los-test-estudiados-en-la-asignatura-1-punto" class="level5">
<h5 class="anchored" data-anchor-id="a.-qué-supuestos-deben-cumplirse-y-mencionad-cómo-podríais-verificarlos-para-que-sea-válido-aplicar-uno-de-los-test-estudiados-en-la-asignatura-1-punto">a. ¿Qué supuestos deben cumplirse y mencionad cómo podríais verificarlos para que sea válido aplicar uno de los test estudiados en la asignatura? (1 punto)</h5>
<p>Para que el contraste de medias multivariante sea válido, se deben cumplir las siguientes condiciones:</p>
<ul>
<li>Las variables que vamos a estudiar, Educación y salud, deben ser independientes.</li>
<li>Ambas variables tienen que ser normales multivariantes con igualdad de matrices de varianzas/covarianzas.</li>
</ul>
<p>Para ver que tenemos indicios de poder considerar las variables como normales multivariantes es comprobar si la Distancia de Mahalanobis al cuadrado es una Chi-cuadrado.</p>
<p>Para ver que las Matrices de varianzas /covarianzas son iguales y se comportan igual podemos hacer un mapa de calor para compararlas.</p>
<p>Por el enunciado podemos interpretar que son independientes, pero sino podríamos ver que la covarianza es 0 y al ser normales la independencia ocurre si y solo si la covarianza es 0.</p>
</section>
<section id="b.-escribid-un-código-en-r-que-implemente-el-contraste-de-comparación-de-medias-multivariantes-apropiado-entre-los-sectores-educación-y-salud-para-las-variables-consideradas.-el-código-debe-calcular-y-mostrar-el-vector-de-medias-muestrales-de-cada-sector-ejecutar-el-contraste.-luego-reportad-el-p-valor-y-tomar-una-decisión-para-alpha0.05-en-el-contexto-del-problema-2-puntos" class="level5">
<h5 class="anchored" data-anchor-id="b.-escribid-un-código-en-r-que-implemente-el-contraste-de-comparación-de-medias-multivariantes-apropiado-entre-los-sectores-educación-y-salud-para-las-variables-consideradas.-el-código-debe-calcular-y-mostrar-el-vector-de-medias-muestrales-de-cada-sector-ejecutar-el-contraste.-luego-reportad-el-p-valor-y-tomar-una-decisión-para-alpha0.05-en-el-contexto-del-problema-2-puntos">b. Escribid un código en R que implemente el contraste de comparación de medias multivariantes apropiado entre los sectores Educación y Salud para las variables consideradas. El código debe calcular y mostrar el vector de medias muestrales de cada sector; ejecutar el contraste. Luego, reportad el p-valor y tomar una decisión para <span class="math inline">\(\alpha=0.05\)</span> en el contexto del problema (2 puntos)</h5>
<p>Vamos a hacer un test de comparación de medias de Hotelling.</p>
<p>Preparamos los datos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hotelling)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'Hotelling' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Cargando paquete requerido: corpcor</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'corpcor' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Adjuntando el paquete: 'Hotelling'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    summarise</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Precision"</span>, <span class="st">"Robustez"</span>, <span class="st">"Productividad"</span>, <span class="st">"Ahorro_tiempo"</span>, <span class="st">"Aceptacion_usuarios"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar solo los sectores Educación y Salud</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>datos_ES <span class="ot">&lt;-</span> datos_taller_evaluado_2 <span class="sc">%&gt;%</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Sector <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Educación"</span>, <span class="st">"Salud"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Sector, <span class="fu">all_of</span>(vars)) <span class="sc">%&gt;%</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">all_of</span>(vars), <span class="sc">~</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(.)))) </span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>datos_educacion <span class="ot">&lt;-</span> <span class="fu">subset</span>(datos_ES, Sector <span class="sc">==</span> <span class="st">"Educación"</span>)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>num_educacion <span class="ot">&lt;-</span> datos_educacion[, <span class="fu">sapply</span>(datos_educacion, is.numeric)]</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>media_educacion <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(num_educacion, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>datos_salud <span class="ot">&lt;-</span> <span class="fu">subset</span>(datos_ES, Sector <span class="sc">==</span> <span class="st">"Salud"</span>)</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>num_salud <span class="ot">&lt;-</span> datos_salud[, <span class="fu">sapply</span>(datos_salud, is.numeric)]</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>media_salud <span class="ot">&lt;-</span> <span class="fu">colMeans</span>(num_salud, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Vector de medias muestrales - Educación:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Vector de medias muestrales - Educación:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(media_educacion)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Precision            Robustez       Productividad       Ahorro_tiempo 
           86.70690            80.26609            84.01781            77.63285 
Aceptacion_usuarios 
           76.06253 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Vector de medias muestrales - Salud:</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Vector de medias muestrales - Salud:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(media_salud)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Precision            Robustez       Productividad       Ahorro_tiempo 
           76.59225            66.85778            69.19468            61.36985 
Aceptacion_usuarios 
           57.69147 </code></pre>
</div>
</div>
<p>Como podemos ver los vectores de medias son diferentes, pero de todas formas hacemos el test de Hotelling para calcular el p-valor para <span class="math inline">\(\alpha=0.05\)</span> que es lo que nos piden:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>test_hotelling <span class="ot">&lt;-</span> <span class="fu">hotelling.test</span>(</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  datos_educacion[, vars],</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  datos_salud[, vars]</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(test_hotelling)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test stat:  206.65 
Numerator df:  5 
Denominator df:  234 
P-value:  0 </code></pre>
</div>
</div>
<p>Por lo tanto rechazamos la hipótesis nula ya que el p-valor es 0. Esto quiere decir que existe, como mínimo, alguna coordenada de los vectores de medias que son diferentes (la diferencia es grande).</p>
</section>
</section>
<section id="representad-de-manera-reducida-los-perfiles-multivariantes-del-uso-de-ia-del-sector-educación-y-del-sector-salud-por-separado.-interpretad-las-componentes-retenidas-explicando-su-posible-significado-práctico-en-el-contexto-del-problema.-justificad-bien-el-procedimiento-3-puntos" class="level4">
<h4 class="anchored" data-anchor-id="representad-de-manera-reducida-los-perfiles-multivariantes-del-uso-de-ia-del-sector-educación-y-del-sector-salud-por-separado.-interpretad-las-componentes-retenidas-explicando-su-posible-significado-práctico-en-el-contexto-del-problema.-justificad-bien-el-procedimiento-3-puntos">3. Representad de manera reducida los perfiles multivariantes del uso de IA del sector Educación y del sector Salud (por separado). Interpretad las componentes retenidas, explicando su posible significado práctico en el contexto del problema. Justificad bien el procedimiento (3 puntos)</h4>
<p>Primero vamos a calcular los valores principales asociados a nuestros datos después de ver en ejercicios anteriores las condiciones de correlación.</p>
<p>Iniciemos separando los valores del df en Educación y Salud. Comenzaremos realizando el PCA para Educación.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(datos_taller_evaluado_2)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 11
  ID     Sector Implementacion Precision Robustez Productividad Ahorro_tiempo
  &lt;chr&gt;  &lt;fct&gt;  &lt;chr&gt;              &lt;dbl&gt;    &lt;dbl&gt;         &lt;dbl&gt;         &lt;dbl&gt;
1 Org001 Salud  Producción          62.4     51.2          87.7          85.4
2 Org002 Salud  Producción          76.8     70.4          91.7          88.5
3 Org003 Salud  Piloto              98.5     85.2          83.5          63.1
4 Org004 Salud  Producción          79.0     63.9          65.8          60.2
5 Org005 Salud  Producción          93.5     78.0          61.2          43.5
6 Org006 Salud  Piloto              89.4     64.2          79.7          71.8
# ℹ 4 more variables: Riesgo_etico &lt;dbl&gt;, Riesgo_legal &lt;dbl&gt;,
#   Aceptacion_usuarios &lt;dbl&gt;, Coste &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>datos_educacion  <span class="ot">&lt;-</span> datos_taller_evaluado_2 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Sector <span class="sc">==</span> <span class="st">"Educación"</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>datos_salud <span class="ot">&lt;-</span> datos_taller_evaluado_2 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Sector <span class="sc">==</span> <span class="st">"Salud"</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>datos_pca_educacion <span class="ot">=</span> <span class="fu">prcomp</span>(datos_educacion[,<span class="dv">4</span><span class="sc">:</span><span class="dv">11</span>], <span class="at">scale =</span> <span class="cn">TRUE</span>)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>lambda <span class="ot">=</span> <span class="fu">get_eigenvalue</span>(datos_pca_educacion)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>lambda</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      eigenvalue variance.percent cumulative.variance.percent
Dim.1  4.4787008        55.983759                    55.98376
Dim.2  2.0372050        25.465063                    81.44882
Dim.3  0.6687939         8.359924                    89.80875
Dim.4  0.2293118         2.866398                    92.67514
Dim.5  0.2152076         2.690096                    95.36524
Dim.6  0.1441879         1.802349                    97.16759
Dim.7  0.1209242         1.511553                    98.67914
Dim.8  0.1056687         1.320859                   100.00000</code></pre>
</div>
</div>
<p>Podemos observar que el primer vap nos da un 55.98% de la información sobre la varianza total. Si añadimos el segundo vap obtenemos el 81.45% de la información. Lo ideal sería considerar las dos primeras componentes sería suficiente para describir bastante bien los datos.</p>
<p>Alternativamente,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_eig</span>(datos_pca_educacion, <span class="at">addlabels =</span> <span class="cn">TRUE</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">100</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in geom_bar(stat = "identity", fill = barfill, color = barcolor, :
Ignoring empty aesthetic: `width`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="taller2_enunciado--1-_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Podemos ver un claro cambio de tendencia en las dimensiones 2 y 3. Por lo que siguiendo la “regla del codo” como una de éstas dos dimensines podríamos obtener una representación de la variabilidad de los datos suficientemente buena.</p>
<p>Representemos ahora el gráfico con las componentes principales en dos dimensiones.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_var</span>(datos_pca_educacion, <span class="at">col.var =</span> <span class="st">"contrib"</span>,</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">gradient.cols =</span> <span class="fu">c</span>(<span class="st">"#00AFBB"</span>, <span class="st">"#E7B800"</span>, <span class="st">"#FC4E07"</span>),</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">repel =</span> <span class="cn">TRUE</span>) </span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.
ℹ The deprecated feature was likely used in the ggpubr package.
  Please report the issue at &lt;https://github.com/kassambara/ggpubr/issues&gt;.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `aes_string()` was deprecated in ggplot2 3.0.0.
ℹ Please use tidy evaluation idioms with `aes()`.
ℹ See also `vignette("ggplot2-in-packages")` for more information.
ℹ The deprecated feature was likely used in the factoextra package.
  Please report the issue at &lt;https://github.com/kassambara/factoextra/issues&gt;.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="taller2_enunciado--1-_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A primera vista nos damos cuenta de que todas las variables están bien representadas ya que se alejan suficiente del orgien de coordenadas de nuestro gráfico.</p>
<p>Observamos que la variable más contribuyen es la de ahorro de tiempo. Mientras que la que menos contribuye sería la asociada a la producción.</p>
<p>Por lo que podemos ver que lo que más interesa en este sector sería ahorrar los máximos costes obteniendo una buena precisión y ahorro de tiempo. Los resultados asociados a la robustez y la productividad no son muy importantes, prefien usar la IA pero no tanto que esta resulte útil.</p>
<p>Además Coste y precisión podemos ver que son mas o menos ortogonales y por tanto independientes a ahorro de tiempo, siendo estas tres las que más contribuyen a los datos.</p>
<p>Notemos además que todas las componentes apuntan hacia la derecha, por lo que, los coeficientes de la primera componente son todos positivos. Los valores que caigan en la región izquierda están peor representados.</p>
<p>Repetimos para el sector de salud.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>datos_pca_salud <span class="ot">=</span> <span class="fu">prcomp</span>(datos_salud[,<span class="dv">4</span><span class="sc">:</span><span class="dv">11</span>], <span class="at">scale =</span> <span class="cn">TRUE</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>lambda <span class="ot">=</span> <span class="fu">get_eigenvalue</span>(datos_pca_salud)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>lambda</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      eigenvalue variance.percent cumulative.variance.percent
Dim.1 4.68131043        58.516380                    58.51638
Dim.2 1.73608935        21.701117                    80.21750
Dim.3 0.76198250         9.524781                    89.74228
Dim.4 0.24965984         3.120748                    92.86303
Dim.5 0.20909534         2.613692                    95.47672
Dim.6 0.14950248         1.868781                    97.34550
Dim.7 0.12318570         1.539821                    98.88532
Dim.8 0.08917435         1.114679                   100.00000</code></pre>
</div>
</div>
<p>Podemos observar que el primer vap nos da un 58.52% de la información sobre la varianza total. Si añadimos el segundo vap obtenemos el 80.22% de la información. Lo ideal sería considerar las dos primeras componentes sería suficiente para describir bastante bien los datos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_eig</span>(datos_pca_salud, <span class="at">addlabels =</span> <span class="cn">TRUE</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">100</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in geom_bar(stat = "identity", fill = barfill, color = barcolor, :
Ignoring empty aesthetic: `width`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="taller2_enunciado--1-_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Podemos ver un claro cambio de tendencia en las dimensiones 2 y 3. Por lo que siguiendo la “regla del codo” como una de éstas dos dimensines podríamos obtener una representación de la variabilidad de los datos suficientemente buena.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_var</span>(datos_pca_salud, <span class="at">col.var =</span> <span class="st">"contrib"</span>,</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">gradient.cols =</span> <span class="fu">c</span>(<span class="st">"#00AFBB"</span>, <span class="st">"#E7B800"</span>, <span class="st">"#FC4E07"</span>),</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">repel =</span> <span class="cn">TRUE</span>) </span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="taller2_enunciado--1-_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Podemos ver que nuevamente todas las variables están bien representadas por estar lejos del origen de coordenadas. Por otro lado, en este sector lo más importante sería la precisión y la robustez así como un ahorro de tiempo (ya que son las de color mas cercano al rojo). Es decir, les interesa obtener los mejores resultados posibles intentando minimizar los tiempos de espera. Esto supondría una mejora del servicio a los pacientes, pudiendo atender mejor a un mayor número de personas. Por otra parte, el factor que menos contribuye sería el coste. Significando que no les importa hacer un mayor gasto si esto hace que podamos salvar a más pacientes.</p>
<p>Además Robustez y precisión podemos ver que son mas o menos ortogonales y por tanto independientes a ahorro de tiempo, siendo estas tres las que más contribuyen a los datos.</p>
<p>Notemos además que todas las componentes apuntan hacia la derecha, por lo que, los coeficientes de la primera componente son todos positivos. Los valores que caigan en la región izquierda están peor representados.</p>
</section>
<section id="a-continuación-os-presentamos-dos-bloques-de-código.-explicad-de-forma-breve-qué-procedimiento-estadístico-se-aplica-en-cada-bloque.-después-interpretad-los-resultados-en-el-contexto-del-problema-describid-qué-perfiles-de-uso-de-ia-emergen-en-el-sector-educación-y-en-qué-se-diferencian-entre-sí.-por-último-compara-ambos-bloques-y-justificad-cuál-de-los-dos-resultados-consideráis-más-adecuado-para-describir-los-perfiles-3-puntos" class="level4">
<h4 class="anchored" data-anchor-id="a-continuación-os-presentamos-dos-bloques-de-código.-explicad-de-forma-breve-qué-procedimiento-estadístico-se-aplica-en-cada-bloque.-después-interpretad-los-resultados-en-el-contexto-del-problema-describid-qué-perfiles-de-uso-de-ia-emergen-en-el-sector-educación-y-en-qué-se-diferencian-entre-sí.-por-último-compara-ambos-bloques-y-justificad-cuál-de-los-dos-resultados-consideráis-más-adecuado-para-describir-los-perfiles-3-puntos">4. A continuación os presentamos dos bloques de código. Explicad de forma breve qué procedimiento estadístico se aplica en cada bloque. Después, interpretad los resultados en el contexto del problema: describid qué perfiles de uso de IA emergen en el sector Educación y en qué se diferencian entre sí. Por último, compara ambos bloques y justificad cuál de los dos resultados consideráis más adecuado para describir los perfiles (3 puntos)</h4>
<section id="bloque-a" class="level5">
<h5 class="anchored" data-anchor-id="bloque-a">Bloque A</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">"datos_taller_evaluado_2.csv"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 240 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (3): ID, Sector, Implementacion
dbl (8): Precision, Robustez, Productividad, Ahorro_tiempo, Riesgo_etico, Ri...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Precision"</span>,<span class="st">"Robustez"</span>,<span class="st">"Productividad"</span>,</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>          <span class="st">"Ahorro_tiempo"</span>,<span class="st">"Aceptacion_usuarios"</span>,</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>          <span class="st">"Riesgo_etico"</span>,<span class="st">"Riesgo_legal"</span>,<span class="st">"Coste"</span>)</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>X_Edu <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Sector <span class="sc">==</span> <span class="st">"Educación"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">all_of</span>(vars)) <span class="sc">%&gt;%</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>X_Edu_sc   <span class="ot">&lt;-</span> <span class="fu">scale</span>(X_Edu)</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_nbclust</span>(X_Edu_sc, <span class="at">FUNcluster =</span> cluster<span class="sc">::</span>pam, <span class="at">method =</span> <span class="st">"wss"</span>) <span class="sc">+</span></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"PAM - WSS (Educación)"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="taller2_enunciado--1-_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>pam_Edu <span class="ot">&lt;-</span> cluster<span class="sc">::</span><span class="fu">pam</span>(X_Edu_sc, <span class="at">k =</span> <span class="dv">4</span>) </span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>pam_Edu</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Medoids:
      ID   Precision   Robustez Productividad Ahorro_tiempo Aceptacion_usuarios
[1,]  71 -1.09219110 -0.8059232   -0.06434179   0.005931296           0.4692885
[2,]  44  0.76781300 -0.3098839    0.10445167   0.682868815           0.8263738
[3,]  38  1.06242739  1.6243818    1.04881332   0.609363870          -0.2711981
[4,] 109  0.01872122  0.4401233   -1.30612866  -1.338987545          -1.6736570
     Riesgo_etico Riesgo_legal      Coste
[1,]   -0.8611678  -0.02700432 -0.9381268
[2,]    0.5553279   0.63005844  0.5080528
[3,]    0.8677973   0.82332402  1.4313399
[4,]   -1.2519386  -1.47941055 -0.6245062
Clustering vector:
  [1] 1 1 2 1 3 1 1 4 1 2 1 2 2 4 4 4 4 2 3 2 2 2 3 1 2 4 3 2 3 3 1 2 2 1 1 3 4
 [38] 3 2 3 2 2 3 2 2 1 3 1 1 2 3 2 3 3 2 2 1 4 1 4 2 4 4 4 3 4 2 2 4 2 1 1 2 3
 [75] 4 4 4 2 1 2 2 2 3 4 2 1 4 4 3 1 2 4 3 1 3 4 1 4 1 4 1 1 2 2 2 2 3 2 4 2 1
[112] 4 4 1 4 2
Objective function:
   build     swap 
1.864003 1.761740 

Available components:
 [1] "medoids"    "id.med"     "clustering" "objective"  "isolation" 
 [6] "clusinfo"   "silinfo"    "diss"       "call"       "data"      </code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_cluster</span>(pam_Edu, <span class="at">data =</span> X_Edu_sc, </span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">ellipse.type =</span> <span class="st">"t"</span>, <span class="at">repel =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Clustering PAM (Educación)"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="taller2_enunciado--1-_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>perfil <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">"perfil_Edu.csv"</span>)<span class="sc">$</span>x</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 116 Columns: 1
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (1): x

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(perfil, pam_Edu<span class="sc">$</span>clustering)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      
perfil  1  2  3  4
     1  2 14  1 14
     2  1  0  8 14
     3 22  8  0  0
     4  3 17 12  0</code></pre>
</div>
</div>
</section>
<section id="bloque-b" class="level5">
<h5 class="anchored" data-anchor-id="bloque-b">Bloque B</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>matriz_distancias <span class="ot">&lt;-</span> <span class="fu">dist</span>(X_Edu_sc, <span class="at">method =</span> <span class="st">"euclidean"</span>)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>h_cluster_average <span class="ot">&lt;-</span> <span class="fu">hclust</span>(<span class="at">d =</span> matriz_distancias, <span class="at">method =</span> <span class="st">"average"</span>)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(matriz_distancias, <span class="fu">cophenetic</span>(h_cluster_average))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7097947</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_dend</span>(h_cluster_average, <span class="at">k =</span> <span class="dv">4</span>, <span class="at">cex =</span> <span class="fl">0.4</span>, <span class="at">rect =</span> <span class="cn">TRUE</span>,</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">main =</span> <span class="st">"Dendrograma (average) - Educación"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="taller2_enunciado--1-_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>average_clusters <span class="ot">&lt;-</span> <span class="fu">cutree</span>(h_cluster_average, <span class="at">k =</span> <span class="dv">4</span>)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(perfil, average_clusters)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      average_clusters
perfil  1  2  3  4
     1  0 16 13  2
     2  0  7 16  0
     3 15 15  0  0
     4  2 29  1  0</code></pre>
</div>
</div>
<p>En este código intentamos agrupar los datos del sector educativo en clusters. En el primer bloque usamos el método de PAM (k-medoides) utilizando 4 clusters según el método del codo. Como hay más de 2 variables, se están representando las 2 primeras componentes de un PCA que explica más de un 80% de la varianza de los datos, por lo que es una buena representación en este sentido. Por otro lado, viendo los clusters observamos que no hay ningún cluster homogéneo ya que se solapan entre ellos, y eso lo podemos observar en la matriz de confusión.</p>
<p>Por otro lado, en el segundo bloque hacemos un clustering jerárquico y lo representamos mediante un dendograma. En este caso, la distancia utilizada es la distancia euclídea y utilizamos el enlace medio. Al igual que antes, utilizamos también 4 clusters. Además, vemos que la distancia cophenetic es 0.7, que es un valor grande y cercano a 1, por lo que también es un buen clustering. Mirando el dendograma, podemos ver que hay un cluster con muchos elementos (el verde), 2 clusters más pequeños, pero de un tamaño razonable (el azul y el morado), y un último clustering, el rojo, que solo contiene 2 elementos y que está a mucha distancia del resto de elementos, por lo que podemos suponer que son outliers. Además, analizando la distribución de los clusters mediante la matriz de confusión vemos que son unos clusters más homogéneos que usando k-medoides.</p>
<p>Teniendo en cuenta que ambos clusters representan bien los datos, nos quedamos con los clusters dados por el dendograma ya que hemos visto que son más homogéneos que los clusters dados por el método de k-medoides.</p>
<p>Además, en el contexto del problema vemos que las IAs de perfil 1 son IAs de baja precisión, pero que tienen poco coste y riesgo ético, por lo que son bastante aceptadas. Las IAs de perfil 2 son las más aceptadas de todas, ya que son bastante precisas y ahorran bastante tiempo, a pesar de tener mayores riesgos y coste. Las IAs de perfil 3 son IAs muy precisas, robustas y productivas, aunque sus altos riesgos y coste hacen que sean algo menos aceptadas. Por último, las IAs de perfil 4 son las menos aceptadas, ya que son poco productivas y consumen mucho tiempo, a pesar de ser las que menor riesgo tienen.</p>
<p>La matriz asociada al algoritmo de PAM tan solo representa de forma muy clara el perfil 3 asociada al clúster 1. La matriz del dendograma tiene el primer clúster que representa muy bien los datos del perfil 1, el cuarto que representa los outliers y el segundo y tercero que representan muy mal los datos.</p>
<p>Teniendo en cuenta que ambos clusters representan mal los datos, el realizado por PAM sería mejor a nivel computacional. Por lo que podríamos escoger este. Si nos interesa una ligera mejoría de la representación podríamos usar el asociado al dendograma.</p>
<p><strong>Instrucciones para entregar:</strong> Un miembro del grupo deberá subir a la tarea de Aula Digital, un único archivo PDF que incluya:<br>
1) los nombres de todos los integrantes, y<br>
2) un enlace al repositorio de GitHub (de cualquiera de los integrantes).</p>
<p>El repositorio deberá contener, como mínimo:<br>
- el archivo fuente <code>.qmd</code>,<br>
- la salida <code>.html</code>, y<br>
- un <code>README.md</code> que describa con claridad el propósito del proyecto y su estructura.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>